//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webProjem.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baslangic
    {
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
    }
}
